config:
  retrobution:
    revision: 11 # Increment this when the resources change
    api-url: https://api.ffretrobution.net
    server-data:
      repository: Retrobution/Retrobution-TableData
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
      - Retro_shared.resourceFile
  beta-20100104:
    revision: 4 # Increment this when the resources change
    nickname: original
    url: https://cdn.dexlabs.systems/ff/big/beta-20100104
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100119:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100119
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100207:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100207
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100307:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100307
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100322:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100322
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100413:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100413
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100502:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100502
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100524:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100524
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100604:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100604
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100616:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100604 # beta-20100616 is broken, use beta-20100604 instead
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100711:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100711
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100728:
    revision: 4 # Increment this when the resources change
    nickname: common-future
    url: https://cdn.dexlabs.systems/ff/big/beta-20100728
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20100909:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20100909
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20101003:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20101003
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20101011:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20101011
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20101028:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20101028
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20101123:
    revision: 4 # Increment this when the resources change
    nickname: latest-future
    url: https://cdn.dexlabs.systems/ff/big/beta-20101123
    server-data:
      repository: OpenFusionProject/tabledata
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - Tutorial.resourceFile
  beta-20110213:
    revision: 4 # Increment this when the resources change
    nickname: earliest-academy
    url: https://cdn.dexlabs.systems/ff/big/beta-20110213
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
  beta-20110314:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110314
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - TrainingGrounds.resourceFile
  beta-20110330:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110330
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
  beta-20110424:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110424
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - TrainingGrounds.resourceFile
  beta-20110523:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110523
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - TrainingGrounds.resourceFile
  beta-20110725:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110725
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - TrainingGrounds.resourceFile
  beta-20110818:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110818
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
      - TrainingGrounds.resourceFile
  beta-20110912:
    revision: 4 # Increment this when the resources change
    url: https://cdn.dexlabs.systems/ff/big/beta-20110912
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
  beta-20111013:
    revision: 4 # Increment this when the resources change
    nickname: academy
    url: https://cdn.dexlabs.systems/ff/big/beta-20111013
    server-data:
      repository: OpenFusionProject/tabledata
      patches:
        - "1013"
    resources:
      - TableData.resourceFile
      - Icons.resourceFile
