areas:
  - [0, 0, 0, 0]
instance:
  - -1
mission:
  - -1
nano:
  - -1
npc:
  - 700
shiny:
  - 129
  - 130
  - 131
  - 132
  - 133
  - 134
  - 135
  - 136
  - 137
  - 138
transportation:
  - -1
backitem:
  - 106
  - 107
  - 108
  - 113
  - 116
  - 151
  - 152
  - 153
  - 154
  - 155
  - 156
  - 157
  - 165
  - 166
  - 168
glassitem:
  - 84
  - 92
  - 109
  - 110
  - 120
hatitem:
  - 249
  - 250
  - 251
  - 252
  - 280
  - 287
  - 330
  - 331
  - 332
  - 354
  - 355
  - 356
  - 357
  - 358
  - 359
pantsitem:
  - 516
  - 517
  - 519
  - 520
  - 521
  - 522
  - 525
  - 526
  - 527
  - 543
  - 544
  - 546
  - 552
  - 553
  - 554
  - 555
  - 556
  - 557
shirtsitem:
  - 539
  - 540
  - 541
  - 555
  - 556
  - 557
  - 558
  - 561
  - 563
  - 564
  - 589
  - 609
  - 610
  - 612
  - 613
  - 614
  - 615
  - 616
  - 617
  - 628
  - 639
  - 640
  - 641
  - 642
  - 643
  - 644
  - 645
  - 646
  - 647
  - 648
  - 649
  - 650
  - 651
  - 652
  - 653
  - 655
  - 656
  - 657
  - 662
  - 663
shoesitem:
  - 523
  - 524
  - 526
  - 527
  - 528
  - 529
  - 532
  - 533
  - 536
  - 549
  - 550
  - 552
  - 555
  - 556
  - 557
  - 558
  - 559
  - 560
weaponitem:
  - 700
  - 701
  - 702
  - 703
  - 704
  - 705
  - 708
  - 709
  - 710
  - 715
  - 720
  - 738
  - 739
  - 740
  - 741
  - 742
  - 743
  - 744
  - 758
  - 759
  - 760
  - 761
  - 762
  - 763
  - 764
vehicleitem:
  - -1
generalitem:
  - -1
chestitem:
  - 1216
