extra_npcs:
  3298:
    name: Jeff the Spider
    event_name: Halloween
    x: 280929
    y: 331223
    z: -5388
    angle: 0
    instance_id: 0
  3310:
    name: Fred Fredburger
    event_name: Halloween
    x: 280929
    y: 331223
    z: -5388
    angle: 0
    instance_id: 0
  3429:
    name: The Grim Spreader
    event_name: Halloween
    x: 280929
    y: 331223
    z: -5388
    angle: 0
    instance_id: 0
  693:
    name: Fusion Ice King's Secret Lair
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  1588:
    name: Fusion Gunter's Secret Lair
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  1597:
    name: The Spire
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  2567:
    name: Ice King
    event_name: Knishmas
    x: 398245
    y: 293811
    z: -4941
    angle: 0
    instance_id: 143
  3269:
    name: Ice King
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  3267:
    name: Gunter
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  3311:
    name: Sour Ron
    event_name: Knishmas
    x: 389997
    y: 357650
    z: -5375
    angle: 0
    instance_id: 0
  3411:
    name: Party Planner
    event_name: BirthdayBash
    x: 389997
    y: 357650
    z: -5375
    angle: 0
    instance_id: 0
  3412:
    name: Retired Birthday Basher
    event_name: BirthdayBash
    x: 389997
    y: 357650
    z: -5375
    angle: 0
    instance_id: 0
  3299:
    name: Blood Gnat Exterminator
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
  3301:
    name: Ext. Heartbreak
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
  3302:
    name: Dr. Estrangelove
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
  3308:
    name: Blood Gnat
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
  3312:
    name: Blood Gnat Queen
    event_name: Valentines
    x: 433176
    y: 403713
    z: -5427
    angle: 0
    instance_id: 0
  3313:
    name: Johnny Bravo
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
extra_mobs:
  3369:
    name: The Weeper
    event_name: None
    x: 267313
    y: 380247
    z: -3710
    angle: -108
    instance_id: 24
  3168:
    name: Lv35 Echo Echo
    event_name: None
    x: 316703
    y: 757442
    z: 5242
    angle: 156
    instance_id: 3
  3171:
    name: Lv36 Echo Echo
    event_name: None
    x: 316703
    y: 757442
    z: 5242
    angle: 156
    instance_id: 3
  54:
    name: Pumpkin Spawn
    event_name: Halloween
    x: 280278
    y: 350155
    z: -4851
    angle: 0
    instance_id: 0
  3415:
    name: Jumbo Pumpkin Spawn
    event_name: Halloween
    x: 280278
    y: 350155
    z: -4851
    angle: 0
    instance_id: 0
  58:
    name: Penguin Pest
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  150:
    name: Frozen Fowl
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  252:
    name: Fusion Ice King
    event_name: Knishmas
    x: 398137
    y: 293401
    z: -4941
    angle: 0
    instance_id: 142
  353:
    name: Fusion Ice King
    event_name: Knishmas
    x: 390744
    y: 296285
    z: -4735
    angle: 0
    instance_id: 144
  344:
    name: Fusion Gunter
    event_name: Knishmas
    x: 398245
    y: 293811
    z: -4941
    angle: 0
    instance_id: 143
  442:
    name: Fusion Gunter
    event_name: Knishmas
    x: 390744
    y: 296285
    z: -4735
    angle: 0
    instance_id: 144
  446:
    name: Frosty Fowl
    event_name: Knishmas
    x: 390744
    y: 296285
    z: -4735
    angle: 0
    instance_id: 144
  1158:
    name: Ice Titan
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
  3408:
    name: Birthday Basher
    event_name: BirthdayBash
    x: 389997
    y: 357650
    z: -5375
    angle: 0
    instance_id: 0
  3409:
    name: Party Popper
    event_name: BirthdayBash
    x: 389997
    y: 357650
    z: -5375
    angle: 0
    instance_id: 0
  3419:
    name: Killer Blood Gnat
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
  3427:
    name: Killer Blood Gnat
    event_name: Valentines
    x: 446970
    y: 302928
    z: -5605
    angle: 0
    instance_id: 0
extra_eggs:
  129:
    name: Secret Snail Egg (Christmas 2019 07 06)
    event_name: Knishmas
    x: 395074
    y: 327118
    z: -5686
    angle: 0
    instance_id: 0
